warning_level:
  type: enum
  default: "warning"
  choices:
    - "warning"
    - "info"
    - "danger"
  description:
    en: "Controls the banner appearance."
warning_content:
  default: >
    <p>
      Warning Title

        <span>
       
      </span>
    </p>
    <p>
      More information about this upcoming change can be found <a href="https://meta.discourse.org/t/-/169672?u=falco">here</a>.
    </p>

  description:
    en: 'Content of the warning banner.'
persistent_dismiss:
  type: bool
  default: false
  description:
    en: 'Make the banner dismiss persistent per device'
