warning_level:
  type: enum
  default: "warning"
  choices:
    - "warning"
    - "info"
    - "danger"
  description:
    en: "Controls the banner appearance."
warning_content:
  default: >
    <p>
      Warning Title

        <span>
       
      </span>
    </p>
    <p>
      Banner content <a href="https://example.com">hyperlink</a>.
    </p>

  description:
    en: 'Content of the warning banner.'
persistent_dismiss:
  type: bool
  default: false
  description:
    en: 'Make the banner dismiss persistent per device'
