warning_level:
  type: enum
  default: "warning"
  choices:
    - "warning"
    - "info"
    - "danger"
  description:
    en: "Controls the banner appearance."
warning_content:
  default: >
    <p>
      Service Status: Down

        <span>
       
      </span>
    </p>
    <p>
      Our team is looking into this issue. Thanks for your patience! <a href="https://coffeechat.discourse.group/c/service-updates/6</a>.
    </p>

  description:
    en: 'Content of the warning for old Android users.'
persistent_dismiss:
  type: bool
  default: false
  description:
    en: 'Make the banner dismiss persistent per device'
