warning_level:
  type: enum
  default: "warning"
  choices:
    - "warning"
    - "info"
    - "danger"
  description:
    en: "Controls the banner appearance."
warning_content:
  default: >
    <p>
      Service Status: Down

        <span>
       
      </span>.
    </p>
    <p>
      Our team is looking into this issue. <a href="https://meta.discourse.org/t/-/169672?u=falco">here</a>.
    </p>

  description:
    en: 'Content of the warning for old Android users.'
persistent_dismiss:
  type: bool
  default: false
  description:
    en: 'Make the banner dismiss persistent per device'
