warning_level:
  type: enum
  default: "warning"
  choices:
    - "warning"
    - "info"
    - "danger"
  description:
    en: "Controls the banner appearance."
warning_content:
  default: >
    <p>
      Service Status: Down

        <span>
          <svg
            class="fa d-icon d-icon-globe-americas svg-icon"
            xmlns="http://www.w3.org/2000/svg"
          >
            <use xlink:href="#globe-americas"></use>
          </svg>
          <span class="relative-time">January 11, 2021 (UTC)</span>
        </span>
      </span>.
    </p>
    <p>
      Our team is looking into this issue. <a href="https://meta.discourse.org/t/-/169672?u=falco">here</a>.
    </p>

  description:
    en: 'Content of the warning for old Android users.'
persistent_dismiss:
  type: bool
  default: false
  description:
    en: 'Make the banner dismiss persistent per device'
